# fly.frontend.toml
app = "madr-web"
primary_region = "lhr"
[build]
  dockerfile = "Dockerfile.frontend"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
