[project]
name = "madr-api"
version = "0.1.0"
description = "Simple romance books management application"
authors = [
    {name = "iamsaturn",email = "arthusjonathan@gmail.com"}
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard] (>=0.141.1,<0.142.0)",
    "pydantic-settings (>=2.15.0,<3.0.0)",
    "psycopg[binary] (>=3.3.4,<4.0.0)",
    "alembic (>=1.19.1,<2.0.0)",
    "sqlalchemy (>=2.0.52,<3.0.0)",
    "pwdlib[argon2] (>=0.3.1,<0.4.0)",
    "pyjwt (>=2.13.0,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "poethepoet (>=0.48.0,<0.49.0)",
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)",
    "ruff (>=0.16.4,<0.17.0)",
    "pytest-asyncio (>=1.4.0,<2.0.0)",
    "testcontainers[postgres] (>=4.15.0,<5.0.0)"
]

[tool.poe.tasks]
run = "fastapi dev madr_api/app.py"
test = "python -m pytest --cov=madr_api --cov-report=term-missing --cov-report=html"
lint = "ruff check ."
format = "ruff format ."