"""add unique constraints to books and novelists

Revision ID: abbdbe0eea55
Revises: 73e6ce0ddb1f
Create Date: 2026-08-29 01:26:37.562650

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "abbdbe0eea55"
down_revision: str | Sequence[str] | None = "73e6ce0ddb1f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "books", ["title"])
    op.create_unique_constraint(None, "novelists", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "novelists", type_="unique")
    op.drop_constraint(None, "books", type_="unique")
    # ### end Alembic commands ###
